// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Model
{
    public partial class BlackList
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public DateTime BanDate { get; set; }
        public string Reason { get; set; }

        public virtual Customer Customer { get; set; }
    }
}