// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BusinessObject.Model
{
    public partial class BlackList
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        [Required]
        public DateTime BanDate { get; set; }
        [Required]
        [MaxLength(100, ErrorMessage = "Reason cannot over 100 characters")]
        public string Reason { get; set; }

        public virtual Customer Customer { get; set; }
    }
}