// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Model
{
    public partial class BookingRecord
    {
        public int Id { get; set; }
        public int BookingRequestId { get; set; }
        public int StaffId { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }

        public virtual BookingRequest BookingRequest { get; set; }
        public virtual staff staff { get; set; }
    }
}