// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Model
{
    public partial class BookingRequest
    {
        public BookingRequest()
        {
            BookingRecord = new HashSet<BookingRecord>();
        }

        public int Id { get; set; }
        public int FieldId { get; set; }
        public int CustomerId { get; set; }
        public DateTime SendDate { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Status { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual FootballField Field { get; set; }
        public virtual ICollection<BookingRecord> BookingRecord { get; set; }
    }
}