// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Model
{
    public partial class FootballField
    {
        public FootballField()
        {
            BookingRequest = new HashSet<BookingRequest>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Capacity { get; set; }
        public double Price { get; set; }
        public string Status { get; set; }
        public string Image { get; set; }

        public virtual ICollection<BookingRequest> BookingRequest { get; set; }
    }
}