// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BusinessObject.Model
{
    public partial class FootballField
    {
        public FootballField()
        {
            BookingRequest = new HashSet<BookingRequest>();
        }

        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(5, 11, ErrorMessage = "Please enter valid integer Number")]
        public int Capacity { get; set; }
        [Range(1, double.MaxValue, ErrorMessage = "Please enter valid doubleNumber")]
        public double Price { get; set; }
        public string Status { get; set; }
        public string Image { get; set; }

        public virtual ICollection<BookingRequest> BookingRequest { get; set; }
    }
}